name = "my-first-rag"
compatibility_date = "2024-07-17"

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "vector-index-my-first-rag"

[[d1_databases]]
binding = "DB"
database_name = "database-my-first-rag"
database_id = "abc"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"
